version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-singlestore
    ports:
      - "4566:4566"  # Edge port for all services
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-west-2
#      - DATA_DIR=/tmp/localstack/data
    volumes:
#      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

#volumes:
#  localstack_data:
#    name: localstack_data